// Type definitions for Mermaid diagrams, parser states, AST nodes, error types, and validation results

// Represents the base structure of a Mermaid diagram
export interface MermaidDiagram {
  type: string;
  title?: string;
  content: any; // This can be refined to specific types depending on the diagram type
}

// Represents the various states the parser might be in
export enum ParserState {
  INITIAL,
  DIAGRAM_STARTED,
  DIAGRAM_ENDED
}

// Represents the nodes in the Abstract Syntax Tree (AST) generated by parsing Mermaid diagrams
export interface ASTNode {
  type: string;
  properties?: Record<string, any>;
  children?: ASTNode[];
}

// Error types encountered during parsing or validation
export interface MermaidError {
  type: string;
  message: string;
  details?: any;
}

// Results of diagram validation
export interface ValidationResults {
  isValid: boolean;
  errors: MermaidError[];
}
